import type { MapDef } from "../../engine/types";

// Maps are authored as DATA (char-grid layers + object placements) — no Tiled
// needed. Each legend char resolves against pack.tiles. Every solid tile/prop
// carries a visible texture and buildings are solid except their entrance, so
// there are no invisible walls.

// === Classroom (interior) 13×10 ===
const classroom: MapDef = {
  id: "classroom",
  kind: "interior",
  tileSize: 32,
  width: 13,
  height: 10,
  bg: "#2b2018",
  legend: {
    "#": "wallC",
    ".": "floorC",
    o: "floorC",
    W: "window",
    c: "clock",
    B: "chalk",
    T: "deskC",
    d: "deskC",
    D: "door",
  },
  ground: [
    "#############",
    "#...........#",
    "#...........#",
    "#...........#",
    "#...........#",
    "#...........o",
    "#...........#",
    "#...........#",
    "#...........#",
    "#############",
  ],
  decor: [
    "...W..c..W...",
    "......B......",
    "......T......",
    "             ",
    "   d d d d   ",
    "            D",
    "   d d d d   ",
    "             ",
    "             ",
    "             ",
  ],
  spawns: {
    "spawn-default": { x: 6, y: 4 },
  },
  exits: [
    {
      id: "door",
      at: { x: 12, y: 5, w: 1, h: 1 },
      to: { map: "town", spawn: "from-school" },
      name: { no: "Døra", en: "The door" },
      prompt: { no: "Gå ut", en: "Go out" },
    },
  ],
  npcs: ["elev1", "elev2"],
  interactables: [],
  ambient: {
    no: "Siste time er snart ferdig. Etterpå venter Ordkryss hjemme.",
    en: "The last lesson is almost over. Ordkryss is waiting at home.",
  },
  cue: {
    delayMs: 4600,
    whenActiveQuest: "siste-time",
    completeQuest: "siste-time",
    bell: true,
    line: { no: "*Det ringer ut.*", en: "*The bell rings.*" },
  },
};

// === Town (world) 26×24 — crossroads centred, generous spacing ===
const town: MapDef = {
  id: "town",
  kind: "world",
  tileSize: 32,
  width: 26,
  height: 24,
  bg: "#3b6b3f",
  legend: {
    ".": "grass",
    ",": "grass2",
    "#": "path",
    "~": "water",
    T: "tree",
    b: "bush",
    "*": "flowers",
    r: "rock",
    L: "lamp",
    n: "bench",
  },
  ground: [
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "............##............",
    "............##............",
    "............##............",
    "............##............",
    "............##............",
    "............##............",
    ".....################.....",
    "............##............",
    "............##........~~~.",
    "............##........~~~.",
    "............##........~~~.",
    "............##............",
    "............##............",
    ".........#..##......#.....",
    ".....################.....",
    "..........................",
  ],
  decor: [
    "TTTTTTTTTTTTTTTTTTTTTTTTTT",
    "T       T       T        T",
    "T       T       T        T",
    "T       T       T        T",
    "T       T       T        T",
    "T       T       T        T",
    "T       T       T        T",
    "T               T        T",
    "T          *  *          T",
    "T        *      *        T",
    "T        *      *        T",
    "T        T               T",
    "T        b               T",
    "T                        T",
    "T                     b  T",
    "T                        T",
    "T                    r   T",
    "T                        T",
    "T                        T",
    "T              L         T",
    "T              n         T",
    "T                        T",
    "T                     TT T",
    "TTTTTTTTTTTTTTTTTTTTTTTTTT",
  ],
  buildings: [
    { id: "dnb", textureKey: "dnb", x: 10, y: 1, wTiles: 5, hTiles: 7, label: "DNB AI Tech" },
    { id: "oslomet", textureKey: "oslomet", x: 2, y: 9, wTiles: 6, hTiles: 5, label: "OsloMet" },
    { id: "nikko", textureKey: "nikko", x: 19, y: 10, wTiles: 4, hTiles: 4, label: "Nikkos hus" },
    { id: "school", textureKey: "school", x: 2, y: 17, wTiles: 6, hTiles: 5, label: "Skolen" },
    { id: "schoolside", textureKey: "workshop", x: 9, y: 18, wTiles: 2, hTiles: 3 },
    { id: "home", textureKey: "house", x: 18, y: 17, wTiles: 4, hTiles: 4, label: "Hjem" },
  ],
  decoSprites: [{ key: "flutterfly", anim: "flutterfly-flap", x: 17, y: 12 }],
  spawns: {
    default: { x: 13, y: 21 },
    "from-school": { x: 6, y: 22 },
    "from-home-town": { x: 18, y: 22 },
  },
  exits: [
    {
      id: "enter-home",
      at: { x: 20, y: 21, w: 1, h: 1 },
      to: { map: "home", spawn: "from-home" },
      name: { no: "Hjem", en: "Home" },
      prompt: { no: "Gå inn", en: "Enter" },
    },
  ],
  npcs: [],
  interactables: [
    "bykryss-sign",
    "dnb-door",
    "oslomet-door",
    "nikko-door",
    "schoolside-door",
    "flutterfly-compile",
  ],
  labels: [],
};

// === Stians hjem (interior) 12×9 ===
const home: MapDef = {
  id: "home",
  kind: "interior",
  tileSize: 32,
  width: 12,
  height: 9,
  bg: "#2b2018",
  legend: {
    "#": "wallH",
    ".": "floorH",
    o: "floorH",
    W: "window",
    B: "bed",
    e: "deskH",
    k: "books",
    g: "rug",
    p: "plant",
    G: "guitar",
    a: "amp",
    m: "mic",
    D: "door",
  },
  ground: [
    "############",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#####oo#####",
  ],
  decor: [
    "...W....W...",
    "            ",
    " B     eek  ",
    "            ",
    "            ",
    "     gg   G ",
    "     gg     ",
    " p      m a ",
    "     D      ",
  ],
  spawns: {
    "from-home": { x: 5, y: 7 },
    default: { x: 5, y: 7 },
  },
  exits: [
    {
      id: "door",
      at: { x: 5, y: 8, w: 2, h: 1 },
      to: { map: "town", spawn: "from-home-town" },
    },
  ],
  npcs: [],
  interactables: ["home-pc", "home-duck"],
  ambient: {
    no: "Hjemme igjen. PC-en venter på pulten.",
    en: "Home again. The PC is waiting on the desk.",
  },
};

export const maps: MapDef[] = [classroom, town, home];
