import type { MapDef } from "../../engine/types";

// Maps are authored as DATA (char-grid layers + object placements) — no Tiled
// needed. Each legend char resolves against pack.tiles. Every solid tile/prop
// carries a visible texture and buildings are solid except their entrance, so
// there are no invisible walls.

// === Classroom (interior) 13×10 ===
const classroom: MapDef = {
  id: "classroom",
  kind: "interior",
  tileSize: 32,
  width: 13,
  height: 10,
  bg: "#2b2018",
  legend: {
    "#": "wallC",
    ".": "floorC",
    o: "floorC",
    W: "window",
    c: "clock",
    B: "chalk",
    T: "deskC",
    d: "deskC",
    D: "door",
  },
  ground: [
    "#############",
    "#...........#",
    "#...........#",
    "#...........#",
    "#...........#",
    "#...........#",
    "#...........#",
    "#...........#",
    "#...........#",
    "######o######",
  ],
  decor: [
    "...W..c..W...",
    "......B......",
    "......T......",
    "             ",
    "...d.d.d.d...",
    "             ",
    "...d.d.d.d...",
    "             ",
    "             ",
    "......D......",
  ],
  spawns: {
    "spawn-default": { x: 6, y: 7 },
  },
  exits: [
    {
      id: "door",
      at: { x: 6, y: 9, w: 1, h: 1 },
      to: { map: "town", spawn: "from-school" },
    },
  ],
  npcs: ["elev1", "elev2"],
  interactables: [],
  ambient: {
    no: "Siste time er snart ferdig. Etterpå venter Ordkryss hjemme.",
    en: "The last lesson is almost over. Ordkryss is waiting at home.",
  },
  cue: {
    delayMs: 4600,
    whenActiveQuest: "siste-time",
    completeQuest: "siste-time",
    bell: true,
    line: { no: "*Det ringer ut.*", en: "*The bell rings.*" },
  },
};

// === Town (world) 24×20 ===
const town: MapDef = {
  id: "town",
  kind: "world",
  tileSize: 32,
  width: 24,
  height: 20,
  bg: "#3b6b3f",
  legend: {
    ".": "grass",
    ",": "grass2",
    "#": "path",
    "~": "water",
    T: "tree",
    b: "bush",
    "*": "flowers",
    r: "rock",
    L: "lamp",
    n: "bench",
  },
  ground: [
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "...........##...........",
    "...........##.~~~.......",
    "...........##.~~~.......",
    "...........##...........",
    "...........##...........",
    "...........##...........",
    ".....################...",
    "...........##...........",
    "...........##...........",
    "...........##...........",
    "...........##...........",
    "...........##......#....",
    "...#################....",
    "........................",
  ],
  decor: [
    "TTTTTTTTT     TTTTTTTTTT",
    "T      TT      TT      T",
    "T b    TT      TT    b T",
    "T   *  TT      TT  *   T",
    "T  b  T          T  b  T",
    "TTTTTTTTT     TTTTTTTTTT",
    "T         *  *         T",
    "T            r   b     T",
    "T        b        T    T",
    "T        L    b        T",
    "T        *    *        T",
    "T       b      T       T",
    "T  T                  TT",
    "T   T   b      b   T   T",
    "T       T      T       T",
    "T        *    *        T",
    "T        L    n        T",
    "T       b             TT",
    "TT                   T T",
    "TTTTTTTTTTTTTTTTTTTTTTTT",
  ],
  buildings: [
    { id: "dnb", textureKey: "dnb", x: 9, y: 0, wTiles: 5, hTiles: 6 },
    { id: "oslomet", textureKey: "oslomet", x: 2, y: 8, wTiles: 6, hTiles: 4 },
    { id: "nikko", textureKey: "nikko", x: 18, y: 9, wTiles: 4, hTiles: 3 },
    { id: "school", textureKey: "school", x: 1, y: 14, wTiles: 6, hTiles: 4 },
    { id: "home", textureKey: "house", x: 17, y: 14, wTiles: 4, hTiles: 3 },
  ],
  decoSprites: [
    { key: "flutterfly", anim: "flutterfly-flap", x: 16, y: 11 },
    { key: "flutterfly", anim: "flutterfly-flap", x: 15, y: 15 },
  ],
  spawns: {
    default: { x: 11, y: 17 },
    "from-school": { x: 5, y: 18 },
    "from-home-town": { x: 17, y: 17 },
  },
  exits: [
    {
      id: "enter-home",
      at: { x: 19, y: 17, w: 1, h: 1 },
      to: { map: "home", spawn: "from-home" },
    },
  ],
  npcs: [],
  interactables: [
    "bykryss-sign",
    "dnb-door",
    "oslomet-door",
    "nikko-door",
    "workshop-door",
  ],
  labels: [
    { text: "DNB AI Tech", x: 11.5, y: 5.3, small: true },
    { text: "OsloMet", x: 4.5, y: 7.4, small: true },
    { text: "Nikkos hus", x: 19.5, y: 8.4, small: true },
    { text: "Skolen", x: 3.5, y: 13.4, small: true },
    { text: "Hjem", x: 18.5, y: 13.4, small: true },
  ],
};

// === Stians hjem (interior) 12×9 ===
const home: MapDef = {
  id: "home",
  kind: "interior",
  tileSize: 32,
  width: 12,
  height: 9,
  bg: "#2b2018",
  legend: {
    "#": "wallH",
    ".": "floorH",
    o: "floorH",
    W: "window",
    B: "bed",
    e: "deskH",
    k: "books",
    g: "rug",
    p: "plant",
    D: "door",
  },
  ground: [
    "############",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#####oo#####",
  ],
  decor: [
    "...W....W...",
    "            ",
    " B     eek  ",
    "            ",
    "            ",
    "     gg     ",
    "     gg     ",
    " p          ",
    "     D      ",
  ],
  spawns: {
    "from-home": { x: 5, y: 7 },
    default: { x: 5, y: 7 },
  },
  exits: [
    {
      id: "door",
      at: { x: 5, y: 8, w: 2, h: 1 },
      to: { map: "town", spawn: "from-home-town" },
    },
  ],
  npcs: [],
  interactables: ["home-pc", "home-duck"],
  ambient: {
    no: "Hjemme igjen. PC-en venter på pulten.",
    en: "Home again. The PC is waiting on the desk.",
  },
};

export const maps: MapDef[] = [classroom, town, home];
