import type { MapDef } from "../../engine/types";

// Maps are authored as DATA (char-grid layers + object placements) — no Tiled
// needed. Each legend char resolves against pack.tiles. Every solid tile/prop
// carries a visible texture and buildings are solid except their entrance, so
// there are no invisible walls.

// === Classroom (interior) 13×10 ===
const classroom: MapDef = {
  id: "classroom",
  kind: "interior",
  tileSize: 32,
  width: 13,
  height: 10,
  bg: "#2b2018",
  legend: {
    "#": "wallC",
    ".": "floorC",
    o: "floorC",
    W: "window",
    c: "clock",
    B: "chalk",
    T: "deskC",
    d: "deskC",
    D: "door",
  },
  ground: [
    "#############",
    "#...........#",
    "#...........#",
    "#...........#",
    "#...........#",
    "#...........o",
    "#...........#",
    "#...........#",
    "#...........#",
    "#############",
  ],
  decor: [
    "...W..c..W...",
    "......B......",
    "......T......",
    "             ",
    "   d d d d   ",
    "            D",
    "   d d d d   ",
    "             ",
    "             ",
    "             ",
  ],
  spawns: {
    "spawn-default": { x: 6, y: 4 },
  },
  exits: [
    {
      id: "door",
      at: { x: 12, y: 5, w: 1, h: 1 },
      to: { map: "town", spawn: "from-school" },
      name: { no: "Døra", en: "The door" },
      prompt: { no: "Gå ut", en: "Go out" },
    },
  ],
  npcs: ["elev1", "elev2"],
  interactables: [],
  ambient: {
    no: "Siste time er snart ferdig. Etterpå venter Ordkryss hjemme.",
    en: "The last lesson is almost over. Ordkryss is waiting at home.",
  },
  cue: {
    delayMs: 4600,
    whenActiveQuest: "siste-time",
    completeQuest: "siste-time",
    bell: true,
    line: { no: "*Det ringer ut.*", en: "*The bell rings.*" },
  },
};

// === Town (world) 26×24 — crossroads centred, generous spacing ===
const town: MapDef = {
  id: "town",
  kind: "world",
  tileSize: 32,
  width: 26,
  height: 24,
  bg: "#3b6b3f",
  legend: {
    ".": "grass",
    ",": "grass2",
    "#": "path",
    "~": "water",
    T: "tree",
    b: "bush",
    "*": "flowers",
    r: "rock",
    L: "lamp",
    n: "bench",
  },
  ground: [
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "..........................",
    "............##............",
    "............##............",
    "............##............",
    "............##............",
    "............##............",
    "............##............",
    ".....################.....",
    "............##............",
    "............##........~~~.",
    "............##........~~~.",
    "............##........~~~.",
    "............##............",
    "............##............",
    ".........#..##......#.....",
    ".....################.....",
    "..........................",
  ],
  decor: [
    "TTTTTTTTTTTTTTTTTTTTTTTTTT",
    "T       T       T        T",
    "T       T       T        T",
    "T       T       T        T",
    "T       T       T        T",
    "T       T       T        T",
    "T       T       T        T",
    "T               T        T",
    "T          *  *          T",
    "T        *      *        T",
    "T        *      *        T",
    "T        T               T",
    "T        b               T",
    "T                        T",
    "T                     b  T",
    "T                        T",
    "T                    r   T",
    "T                        T",
    "T                        T",
    "T              L         T",
    "T              n         T",
    "T                        T",
    "T                     TT T",
    "TTTTTTTTTTTTTTTTTTTTTTTTTT",
  ],
  buildings: [
    {
      id: "dnb",
      textureKey: "dnb",
      x: 10,
      y: 1,
      wTiles: 5,
      hTiles: 7,
      label: "DNB AI Tech",
    },
    {
      id: "oslomet",
      textureKey: "oslomet",
      x: 2,
      y: 9,
      wTiles: 6,
      hTiles: 5,
      label: "OsloMet",
    },
    {
      id: "nikko",
      textureKey: "nikko",
      x: 19,
      y: 10,
      wTiles: 4,
      hTiles: 4,
      label: "Nikkos hus",
    },
    {
      id: "school",
      textureKey: "school",
      x: 2,
      y: 17,
      wTiles: 6,
      hTiles: 5,
      label: "Skolen",
    },
    {
      id: "schoolside",
      textureKey: "workshop",
      x: 9,
      y: 18,
      wTiles: 2,
      hTiles: 3,
    },
    {
      id: "home",
      textureKey: "house",
      x: 18,
      y: 17,
      wTiles: 4,
      hTiles: 4,
      label: "Hjem",
    },
  ],
  decoSprites: [
    { key: "flutterfly", anim: "flutterfly-flap", x: 17, y: 12, wander: true },
  ],
  spawns: {
    default: { x: 13, y: 21 },
    "from-school": { x: 6, y: 22 },
    "from-home-town": { x: 18, y: 22 },
    "from-oslomet": { x: 5, y: 15 },
    "from-workshop": { x: 9, y: 22 },
    "from-dnb": { x: 12, y: 9 },
    "from-nikko": { x: 21, y: 15 },
  },
  exits: [
    {
      id: "enter-home",
      at: { x: 20, y: 21, w: 1, h: 1 },
      to: { map: "home", spawn: "from-home" },
      name: { no: "Hjem", en: "Home" },
      prompt: { no: "Gå inn", en: "Enter" },
    },
    {
      id: "enter-oslomet",
      at: { x: 5, y: 14, w: 1, h: 1 },
      to: { map: "oslomet", spawn: "from-town" },
      name: { no: "OsloMet", en: "OsloMet" },
      prompt: { no: "Gå inn", en: "Enter" },
      lock: {
        id: "oslomet-gate",
        requires: { allSkills: ["grunnleggende-programmering"] },
        lockedText: {
          no: "OsloMet åpner når grunnmuren i programmering er på plass.",
          en: "OsloMet opens once the programming foundation is in place.",
        },
      },
    },
    {
      id: "enter-workshop",
      at: { x: 9, y: 21, w: 1, h: 1 },
      to: { map: "workshop", spawn: "from-town" },
      name: { no: "Workshop", en: "Workshop" },
      prompt: { no: "Gå inn", en: "Enter" },
      lock: {
        id: "workshop-gate",
        requires: { flag: "open:workshop" },
        lockedText: {
          no: "Workshoprommet er låst. Du trenger et metodeoppdrag fra OsloMet først.",
          en: "The workshop room is locked. You need a method assignment from OsloMet first.",
        },
      },
    },
    {
      id: "enter-dnb",
      at: { x: 12, y: 8, w: 1, h: 1 },
      to: { map: "dnb", spawn: "from-town" },
      name: { no: "DNB AI Tech", en: "DNB AI Tech" },
      prompt: { no: "Gå inn", en: "Enter" },
      lock: {
        id: "dnb-gate",
        requires: { flag: "open:dnb" },
        lockedText: {
          no: "Resepsjonen tar bare imot komplette søknadspakker.",
          en: "The reception only accepts complete application packages.",
        },
      },
    },
    {
      id: "enter-nikko",
      at: { x: 21, y: 14, w: 1, h: 1 },
      to: { map: "nikko-house", spawn: "from-town" },
      name: { no: "Nikkos hus", en: "Nikko's house" },
      prompt: { no: "Gå inn", en: "Enter" },
      lock: {
        id: "nikko-gate",
        requires: { allQuests: ["laererworkshop"] },
        lockedText: {
          no: "Det er noen hjemme, men du har ingen grunn til å gå inn ennå.",
          en: "Someone's home, but you have no reason to go in yet.",
        },
      },
    },
  ],
  npcs: [],
  interactables: ["bykryss-sign", "nikko-invite"],
  labels: [],
};

// === Stians hjem (interior) 12×9 ===
const home: MapDef = {
  id: "home",
  kind: "interior",
  tileSize: 32,
  width: 12,
  height: 9,
  bg: "#2b2018",
  legend: {
    "#": "wallH",
    ".": "floorH",
    o: "floorH",
    W: "window",
    B: "bed",
    e: "deskH",
    k: "books",
    g: "rug",
    p: "plant",
    G: "guitar",
    a: "amp",
    m: "mic",
    D: "door",
  },
  ground: [
    "############",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#####o######",
  ],
  decor: [
    "...W....W...",
    "            ",
    " B     eek  ",
    "            ",
    "            ",
    "     gg   G ",
    "     gg     ",
    " p      m a ",
    "     D      ",
  ],
  spawns: {
    "from-home": { x: 5, y: 7 },
    default: { x: 5, y: 7 },
  },
  exits: [
    {
      id: "door",
      at: { x: 5, y: 8, w: 1, h: 1 },
      to: { map: "town", spawn: "from-home-town" },
    },
  ],
  npcs: [],
  interactables: [
    "home-pc",
    "home-pc-pd",
    "home-pc-portfolio",
    "home-pc-idle",
    "home-duck",
  ],
  ambient: {
    no: "Hjemme igjen. PC-en venter på pulten.",
    en: "Home again. The PC is waiting on the desk.",
  },
};

// === OsloMet — masterstudio (interior) 13×9 ===
const oslomet: MapDef = {
  id: "oslomet",
  kind: "interior",
  tileSize: 32,
  width: 13,
  height: 9,
  bg: "#241d16",
  legend: {
    "#": "wallC",
    ".": "floorC",
    o: "floorC",
    W: "window",
    B: "chalk",
    e: "deskC",
    g: "rug",
    p: "plant",
    D: "door",
  },
  ground: [
    "#############",
    "#...........#",
    "#...........#",
    "#...........#",
    "#...........#",
    "#...........#",
    "#...........#",
    "#...........#",
    "######o######",
  ],
  decor: [
    "...W.....W...",
    "......B......",
    "             ",
    "          e  ",
    "             ",
    "     gg      ",
    "             ",
    " p           ",
    "      D      ",
  ],
  spawns: {
    "from-town": { x: 6, y: 7 },
    default: { x: 6, y: 7 },
  },
  exits: [
    {
      id: "door",
      at: { x: 6, y: 8, w: 1, h: 1 },
      to: { map: "town", spawn: "from-oslomet" },
      name: { no: "Døra", en: "The door" },
      prompt: { no: "Gå ut", en: "Go out" },
    },
  ],
  npcs: [],
  interactables: [
    "oslomet-board",
    "oslomet-klar",
    "oslomet-method",
    "oslomet-veileder-pd",
    "oslomet-veileder-master",
    "kari",
  ],
  ambient: {
    no: "Masterstudioet. Her ble uklare behov til noe man kan ta på.",
    en: "The master's studio. Where unclear needs became something tangible.",
  },
  cue: {
    delayMs: 700,
    whenActiveQuest: "til-oslomet",
    completeQuest: "til-oslomet",
    line: { no: "*Du er inne på OsloMet.*", en: "*You're inside OsloMet.*" },
  },
};

// === Skolen — lærerworkshop (interior) 12×9 ===
const workshop: MapDef = {
  id: "workshop",
  kind: "interior",
  tileSize: 32,
  width: 12,
  height: 9,
  bg: "#241d16",
  legend: {
    "#": "wallC",
    ".": "floorC",
    o: "floorC",
    W: "window",
    B: "chalk",
    T: "deskC",
    g: "rug",
    k: "books",
    p: "plant",
    D: "door",
  },
  ground: [
    "############",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#####o######",
  ],
  decor: [
    "...W....W...",
    "......B.....",
    "            ",
    "            ",
    "    TTTT    ",
    "            ",
    "            ",
    " k          ",
    "     D      ",
  ],
  spawns: {
    "from-town": { x: 5, y: 7 },
    default: { x: 5, y: 7 },
  },
  exits: [
    {
      id: "door",
      at: { x: 5, y: 8, w: 1, h: 1 },
      to: { map: "town", spawn: "from-workshop" },
      name: { no: "Døra", en: "The door" },
      prompt: { no: "Gå ut", en: "Go out" },
    },
  ],
  npcs: [],
  interactables: ["ws-teacher1", "ws-teacher2", "ws-teacher3", "ws-board"],
  ambient: {
    no: "Lærerworkshop. Journey map, lapper og friske øyne på behovene.",
    en: "Teacher workshop. A journey map, sticky notes and fresh eyes on the needs.",
  },
};

// === DNB AI Tech — resepsjon (interior) 12×9 ===
const dnb: MapDef = {
  id: "dnb",
  kind: "interior",
  tileSize: 32,
  width: 12,
  height: 9,
  bg: "#1c2230",
  legend: {
    "#": "wallC",
    ".": "floorC",
    o: "floorC",
    W: "window",
    T: "deskC",
    p: "plant",
    D: "door",
  },
  ground: [
    "############",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#####o######",
  ],
  decor: [
    "...W....W...",
    "            ",
    "   TTTT     ",
    "            ",
    "            ",
    "            ",
    " p          ",
    "            ",
    "     D      ",
  ],
  spawns: {
    "from-town": { x: 5, y: 7 },
    default: { x: 5, y: 7 },
  },
  exits: [
    {
      id: "door",
      at: { x: 5, y: 8, w: 1, h: 1 },
      to: { map: "town", spawn: "from-dnb" },
      name: { no: "Døra", en: "The door" },
      prompt: { no: "Gå ut", en: "Go out" },
    },
  ],
  npcs: [],
  interactables: ["dnb-deliver", "dnb-egg"],
  ambient: {
    no: "DNB AI Tech — resepsjonen. Søknadsbunken ligger på disken.",
    en: "DNB AI Tech — the reception. The stack of applications sits on the counter.",
  },
};

// === Nikkos hus (interior) 12×9 — to arbeidsstasjoner side om side ===
const nikkoHouse: MapDef = {
  id: "nikko-house",
  kind: "interior",
  tileSize: 32,
  width: 12,
  height: 9,
  bg: "#2b2018",
  legend: {
    "#": "wallH",
    ".": "floorH",
    o: "floorH",
    W: "window",
    e: "deskH",
    g: "rug",
    p: "plant",
    D: "door",
  },
  ground: [
    "############",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#..........#",
    "#####o######",
  ],
  decor: [
    "...W....W...",
    "            ",
    "    eeee    ",
    "            ",
    "     gg     ",
    "     gg     ",
    " p          ",
    "            ",
    "     D      ",
  ],
  decoSprites: [{ key: "pc", x: 5, y: 2 }],
  spawns: {
    "from-town": { x: 5, y: 7 },
    default: { x: 5, y: 7 },
  },
  exits: [
    {
      id: "door",
      at: { x: 5, y: 8, w: 1, h: 1 },
      to: { map: "town", spawn: "from-nikko" },
      name: { no: "Døra", en: "The door" },
      prompt: { no: "Gå ut", en: "Go out" },
    },
  ],
  npcs: [],
  interactables: ["nikko-desk", "nikko-station"],
  ambient: {
    no: "Nikkos hus. To skjermer står klare side om side.",
    en: "Nikko's house. Two screens stand ready side by side.",
  },
};

export const maps: MapDef[] = [
  classroom,
  town,
  home,
  oslomet,
  workshop,
  dnb,
  nikkoHouse,
];
